query transferRequest($id: ID) {
	transferRequest(id: $id) {
		vacancy {
			id
			status
			isEngine
			numOfApplicants
			fireStation {
				id
				name
			}
		}
		requestSubmitter {
			id
			firstName
			lastName
		}
		sentDate
		approvalDate
		applicationStatus
	}
}