query Reports {
	reports {
		id
		submitter {
			id
			firstName
			lastName
		}
		fireStation{
			id
			name
		}
		typeOfIncident
		createdAt
		timeDispatched
		timeArrived
		wasExposedToChem
		wasFireRetardantPresent
		chemicalExposureNotes
		actionsOfPrimaryTeam
		actionsOfSecondaryTeam
		descriptionOfEvent
	}
}